---
apiVersion: v1
kind: Service
metadata:
  name: python-app-deploy
spec:
  selector:
    app: python-app
  type: LoadBalancer
  ports:
    - name: python-app-port
      port: 3030
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deploy
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: ${img}
        ports:
        - containerPort: 8000